### ISSUE TITLE
Why desaturate the image?

### ISSUE THREAD

**Issue by YinlinHu** [innodatalabs/redstork-ui#1]
Thanks for the great attempts for the python wrapping of PDFium.
One minor question, after desaturating the image, the output will be colorless. For a normal user, color PDFs will be more preferable. Do you have any particular reasons for that operation?

https://github.com/innodatalabs/redstork-ui/blob/2f5f23ac4c0f017cca35b69f686aab1eb6528ef3/ui/presenter/page_presenter.py#L30

**Comment by mkroutikov** [comment]
Good question. I draw color annotations on top of PDF page, and found that page colors distract, hence desaturate.

Here we primarily work with text PDFs and removing color (illustrations, charts, some headings) does not hurt.

That said, to desaturate or not should be a user decision (via settings). Feel free to open a feature request for that.
